package com.example.myapplication.model

import android.os.Parcelable
import kotlinx.parcelize.Parcelize
import kotlinx.parcelize.RawValue


@Parcelize
data class ProductsItem(
    val _links: @RawValue Links,
    val attributes: @RawValue List<Any>,
    val average_rating: String,
    val backordered: Boolean,
    val backorders: String,
    val backorders_allowed: Boolean,
    val button_text: String,
    val catalog_visibility: String,
    val categories: @RawValue List<Category>,
    val cross_sell_ids: @RawValue List<Any>,
    val date_created: String,
    val date_created_gmt: String,
    val date_modified: String,
    val date_modified_gmt: String,
    val date_on_sale_from: @RawValue Any?,
    val date_on_sale_from_gmt: @RawValue Any?,
    val date_on_sale_to: @RawValue Any?,
    val date_on_sale_to_gmt: @RawValue Any?,
    val default_attributes: @RawValue List<Any>,
    val description: String,
    val dimensions: @RawValue Dimensions,
    val download_expiry: Int,
    val download_limit: Int,
    val downloadable: Boolean,
    val downloads: @RawValue List<Any>,
    val external_url: String,
    val featured: Boolean,
    val grouped_products: @RawValue List<Any>,
    val id: Int,
    val images: @RawValue List<Image>,
    val low_stock_amount: @RawValue Any?,
    val manage_stock: Boolean,
    val menu_order: Int,
    val meta_data: @RawValue List<Any>?,
    val name: String,
    val on_sale: Boolean,
    val parent_id: Int,
    val permalink: String,
    val price: String,
    val price_html: String,
    val purchasable: Boolean,
    val purchase_note: String,
    val rating_count: Int,
    val regular_price: String,
    val related_ids: List<Int>,
    val reviews_allowed: Boolean,
    val sale_price: String,
    val shipping_class: String,
    val shipping_class_id: Int,
    val shipping_required: Boolean,
    val shipping_taxable: Boolean,
    val short_description: String,
    val sku: String,
    val slug: String,
    val sold_individually: Boolean,
    val status: String,
    val stock_quantity: @RawValue Any?,
    val stock_status: String,
    val tags: @RawValue List<Tag>,
    val tax_class: String,
    val tax_status: String,
    val total_sales: Int,
    val type: String,
    val upsell_ids: @RawValue List<Any>?,
    val variations: @RawValue List<Any>?,
    val virtual: Boolean,
    val weight: String
) : Parcelable